### New User
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "username": "user",
    "password": "password"
}

### LOgin and generate Token

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "user2",
    "password": "password"
}

### Tokens
@token1 = 7a6360c1fe100820c1e11b1baa29498096320783ac7597c1639091f3c20d7c02
@token2 = 1eaba78a75ccb3c8be004003078584fad83c6facc807e69dd86744f1adbeec6a
@token3 = 79ad9fabe835736401d2715264de3a2f76121399e25db52044539bceed056904

@token_from_db = a36b609622076ae17ee5b011e86fb4ef9e64a2f4232aba4faa0387d96f76acf8116418c81f547289eb1ca613733fefd70b8ae358a1fbf0bdaeaaad3e95751416
###

### Test without Token

GET http://127.0.0.1:8000/api/collections/

### Test with Token
GET http://127.0.0.1:8000/api/collections/
Authorization: Token {{{{token_from_db}}}}

###
@subject = Subject2
@category = cat2

### Create Collection

POST http://127.0.0.1:8000/api/collections/
Authorization: Token {{token2}}
Content-Type: application/json

{
    "name": "{{subject}} Flashcards",
    "description": "Collection of {{subject}} terms and definitions",
    "category": "{{category}}"
}

### Create cards

@collection = 1
@cardNumber = 2
@front = fron_{{cardNumber}}
@back = back_{{cardNumber}}


###

POST http://127.0.0.1:8000/api/collections/{{collection}}/cards/
Authorization: Token {{token1}}
Content-Type: application/json

{
    "front": "{{front}}",
    "back": "{{back}}"
}


### Get collection Cards
GET http://127.0.0.1:8000/api/collections/{{collection}}/cards/
Authorization: Token {{token1}}

### Get specific card
GET http://127.0.0.1:8000/api/collections/{{collection}}/cards/2/
Authorization: Token {{token1}}

### Edit specific card
PATCH  http://127.0.0.1:8000/api/collections/{{collection}}/cards/2/
Authorization: Token {{token1}}
Content-Type: application/json

{
    "back" : "new back"
}

### Edit specific collection
PATCH  http://127.0.0.1:8000/api/collections/1/
Authorization: Token {{token1}}
Content-Type: application/json

{
    "description" : "new description"
}

### Delete collection

DELETE http://127.0.0.1:8000/api/collections/7/
Authorization: Token {{token1}}

### Delete card

DELETE http://127.0.0.1:8000/api/collections/2/cards/4/
Authorization: Token {{token1}}


###

POST http://127.0.0.1:8000/api/users/logout/
Authorization: Token ce337e2f763bba16253dfef35c29e473187f328768c6a1568fbba0d3ab1538b2

###



###


###

###

POST http://127.0.0.1:8000/api/users/logoutall/
Authorization: Token {{token1}}

###

